# Generated by Django 5.2.13 on 2026-04-20 15:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, unique=True)),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "current_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "demand_status",
                    models.CharField(
                        choices=[
                            ("ALTA", "Alta"),
                            ("ESTABLE", "Estable"),
                            ("BAJA", "Baja"),
                        ],
                        default="ESTABLE",
                        max_length=10,
                    ),
                ),
                (
                    "trend",
                    models.CharField(
                        choices=[
                            ("SUBE", "Sube"),
                            ("ESTABLE", "Estable"),
                            ("BAJA", "Baja"),
                        ],
                        default="ESTABLE",
                        max_length=10,
                    ),
                ),
                ("regression_a", models.FloatField(default=0)),
                ("regression_b", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TurnRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("turn_number", models.PositiveIntegerField()),
                (
                    "observed_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "quantity_traded",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("expected_demand", models.FloatField(default=0)),
                ("delta_q", models.FloatField(default=0)),
                ("adjustment_factor", models.FloatField(default=0.25)),
                (
                    "applied_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("regression_a_used", models.FloatField(default=0)),
                ("regression_b_used", models.FloatField(default=0)),
                ("model_recalculated", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turns",
                        to="mercado.resource",
                    ),
                ),
            ],
            options={
                "ordering": ["-turn_number", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("resource", "turn_number"),
                        name="unique_turn_per_resource",
                    )
                ],
            },
        ),
    ]
